Add the childrenOf query filter for search results to the allowed filters.
Ensembl/ols-client pull request #29
Opened 2021-01-26 08:38 UTC by cuyt

* Allow the 'childrenOf' filter in the allowed set of filters
* Add appropriate type checking for this filter
* Add tests for search result filtering behaviour
* Fix some type assertions in the original results filter lists.

2021-01-28 08:24 UTC, cuyt commented
Hello @marcoooo, 
On our project we've started to make use of this excellent wrapper library around the OLS API. I noticed a gap in the allowed filters on search results, namely the 'chlidrenOf' filter (as described on https://www.ebi.ac.uk/ols/docs/api), which I'd like to make use of. 
This PR simple lets the filter pass the results filter checks. It includes basic unit tests for the filter on one of the ontologies (Phi) in the OLS-docker image. 
I've found a couple of instances where I think the filter type check has a typo. One of the commits is a presumed fix for this.
This is my first time make a PR on github, so please let me know if anything is missing or should be done differently. 
I would greatly appreciate if you have a chance to look at the PR and if satisfactory, merge into the main repo.

Best regards,
Thomas

2021-01-28 08:26 UTC, marcoooo commented
Hi Thomas, thanks for this, we'll have a look to your PR soon.

2021-01-28 08:27 UTC, marcoooo commented on ebi/ols/api/base.py
> +            elif type(filters['fieldList']) is set:
Well spotted! :-)

2021-01-28 14:50 UTC, radome requested changes
Hi @cuyt, thank you for you PR.

I've added some small suggestions in order for the test suite to be consistent.

@marcoooo in general IMO we should prefer `isinstance` over `type` (see this interesting [post](https://switowski.com/blog/type-vs-isinstance)). Also we should probably review the use of `assert` and `AssertionError` in the code. I'll work on a PR about that and updating the `README` as well.

2021-01-28 14:50 UTC, radome commented on tests/test_basic.py
> +        assert(actual_iris == expected_iris)
```suggestion
        self.assertEqual(actual_iris, expected_iris)
```

2021-01-28 14:50 UTC, radome commented on tests/test_basic.py
> +        assert(actual_iris == expected_iris)
```suggestion
        self.assertEqual(actual_iris, expected_iris)
```

2021-01-28 14:50 UTC, radome commented on tests/test_basic.py
> +        assert(actual_iris == expected_iris)
```suggestion
        self.assertEqual(actual_iris, expected_iris)
```

2021-01-28 16:11 UTC, cuyt commented
Thanks for the quick review @radome! I've applied your suggestions and updated the `filter_response` `type` testing to `isinstance` per your suggestion.

On a different note: I've seen that the API also has the `api/select` endpoint which does some different kind of search (I'm not sure how it differs exactly from the `search` endpoint). At this point I don't think the ols-client wraps the `select` endpoint. Do you know if this is planned for the future?

Cheers,
Thomas

2021-01-28 17:21 UTC, marcoooo commented
> Thanks for the quick review @radome! I've applied your suggestions and updated the `filter_response` `type` testing to `isinstance` per your suggestion.
> 
> On a different note: I've seen that the API also has the `api/select` endpoint which does some different kind of search (I'm not sure how it differs exactly from the `search` endpoint). At this point I don't think the ols-client wraps the `select` endpoint. Do you know if this is planned for the future?
> 
> Cheers,
> Thomas

We'll be happy to have a PR coming in proposing this integration :-), I am afraid we dedicated our first effort to wrapp the most needed services for our Ensembl requirements. We may integrate it in the future, but I can't tell you exactly when.

2021-01-29 10:18 UTC, radome approved these changes

2021-02-02 16:50 UTC, merged